server:
  port: 8088
spring:
  # 配置数据源
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    # redis配置
  redis:
    database: 2
    lettuce:
      pool:
        max-active: 8  # 连接池中最大连接,默认为8
        max-idle: 8    # 连接池中最大空闲连接,默认8
        max-wait: -1ms # 连接池最大的阻塞时间,默认-1,负数表示没有限制
        min-idle: 0    # 连接池中最小空闲连接,默认0
    host: 120.77.204.187 # 地址
    port: 9007 # 端口
    password: amwiqqqq120#$%^&* # 密码
 #jwt配置
jwt:
  secret: JWTSecret #密钥key
  tokenHeader: Authorization #token头部
  tokenPrefix: xlh- # token前缀字符
  expiration: 86400 # 过期时间,单位是秒,1天后过期=86400 7天后过期=604800
  antMatchers: /index/**,/login/**,/favion.ico #配置不需要认证的接口/资源
mybatis-plus:
  # xml扫描，多个目录用逗号或者分号分隔（告诉 Mapper 所对应的 XML 文件位置）
  mapper-locations: classpath:mapper/*.xml
  # 以下配置均有默认值,可以不设置
  global-config:
    db-config:
      #主键类型 AUTO:"数据库ID自增" INPUT:"用户输入ID",ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: AUTO
      #字段策略 IGNORED:"忽略判断"  NOT_NULL:"非 NULL 判断")  NOT_EMPTY:"非空判断"
      field-strategy: NOT_EMPTY
      #数据库类型
      db-type: MYSQL
  configuration:
    # 是否开启自动驼峰命名规则映射:从数据库列名到Java属性驼峰命名的类似映射
    map-underscore-to-camel-case: true
    # 返回map时true:当查询数据为空时字段返回为null,false:不加这个查询数据为空时，字段将被隐藏
    call-setters-on-nulls: true
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
